### ISSUE TITLE
Is the varnam API dead?

### ISSUE THREAD

**Issue by Aditya-ds-1806** [varnamproject/varnamproject.github.io#1]
Will the endpoint http://api.varnamproject.com/tl be maintained? It goes down very frequently

**Comment by subins2000** [comment]
Pinging @navaneeth

**Comment by navaneeth** [comment]
Thanks for reporting. It should be good now. Linode took the server down for maintenance. @subins2000

**Comment by Aditya-ds-1806** [comment]
Can I ask how reliable this endpoint is? I have observed similar things happen frequently in the past

**Comment by navaneeth** [comment]
Usually reliable. I haven't observed this going down much. Sometime Linode does maintenance on systems which cause disruption. We can run this with a more HA setup also

**Comment by subins2000** [comment]
The endpoint is very reliable now. Closing this issue
